name: capstone-py310
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - plotly
  - streamlit
  - pyvista
  - vtk
  - geopandas
  - shapely
  - pyproj
  - gdal
  - fiona
  - rasterio
  - rtree
  - pip:
      - -r requirements.txt
